[package]
name = "rust-chess"
version = "0.1.16"
edition = "2021"

[dependencies]
rand = "0.7.2"
substring = "1.4.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.dev]
opt-level = 3